### ISSUE TITLE
unable to read multicast interface

### ISSUE THREAD

**Issue by mrefky** [robaho/go-trader#12]
Running exchange generates error "panic unable to read multicast interface"

**Comment by robaho** [comment]
You need to provide the full panic trace or I cannot help.

You may need to edit the settings in configs/ to make it work on your machine.

**Comment by robaho** [comment]
The code may need to be updated for Go modules. Go changes a lot of infra all the time, so things break.

**Comment by mrefky** [comment]
Thanks I managed to correct it and all works as expected . Thanks for sharing this .

**Comment by robaho** [comment]
I am happy you find it useful.
