### ISSUE TITLE
Unable to compile due to gocui version 

### ISSUE THREAD

**Issue by napoleon665** [robaho/go-trader#13]
Hi @robaho ,

Im see that you have your own custom fork however when I call `go install` I get the following errors:

<img width="807" alt="image" src="https://github.com/user-attachments/assets/aa59f841-8574-4490-ac0f-80932f138840">

**Comment by napoleon665** [comment]
@robaho Im confused because it should work as your fork has the missing methods - such as maxlines

https://github.com/robaho/gocui/blob/24bdf44ec8485b466af27750a479458c0dc4ab95/view.go#L76

**Comment by robaho** [comment]
yea, I am confused as well. I am looking into it.

**Comment by robaho** [comment]
It is fixed now. I needed to make some changes to the module versions. Thanks for reporting, I guess this stopped compiling when I added module support to `go-trader`

**Comment by napoleon665** [comment]
Thanks perfect @robaho , I actually fixed these locally was wondering if u want help maintaining this ?

**Comment by robaho** [comment]
> Thanks perfect @robaho , I actually fixed these locally was wondering if u want help maintaining this ?

I am always up for PRs. I have thought about a few enhancements, like adding a live exchange connection (e.g. Coinbase), and a basic portfolio manager, to allow easier live and backtest strategy testing.
