### ISSUE TITLE
error to build client library

### ISSUE THREAD

**Issue by ankitpatelce** [robaho/go-trader#4]
Hello ,

Thanks to made this fantastic financial module. I like your way of coding.
when I run  "go install github.com/robaho/go-trader/cmd/client", I have  got errors like below.
Please look into it. Thanks

# github.com/robaho/go-trader/cmd/client
github.com/robaho/go-trader/cmd/client/main.go:32:32: book.Bids[0].Price.StringFixed undefined (type fixed.Fixed has no field or method StringFixed)
github.com/robaho/go-trader/cmd/client/main.go:36:32: book.Asks[0].Price.StringFixed undefined (type fixed.Fixed has no field or method StringFixed)
github.com/robaho/go-trader/cmd/client/main.go:48:86: book.Asks[i].Price.StringFixed undefined (type fixed.Fixed has no field or method StringFixed)
github.com/robaho/go-trader/cmd/client/main.go:52:86: book.Bids[i].Price.StringFixed undefined (type fixed.Fixed has no field or method StringFixed)
github.com/robaho/go-trader/cmd/client/main.go:119:23: order.Remaining.Equals undefined (type fixed.Fixed has no field or method Equals)
github.com/robaho/go-trader/cmd/client/main.go:122:114: order.Price.StringFixed undefined (type fixed.Fixed has no field or method StringFixed)
github.com/robaho/go-trader/cmd/client/main.go:149:17: trade.Price.Equals undefined (type fixed.Fixed has no field or method Equals)
github.com/robaho/go-trader/cmd/client/main.go:151:36: cannot use lp (type decimal.Decimal) as type fixed.Fixed in argument to trade.Price.GreaterThan
github.com/robaho/go-trader/cmd/client/main.go:157:30: cannot use trade.Price (type fixed.Fixed) as type decimal.Decimal in assignment
github.com/robaho/go-trader/cmd/client/main.go:159:116: trade.Price.StringFixed undefined (type fixed.Fixed has no field or method StringFixed)
github.com/robaho/go-trader/cmd/client/main.go:159:116: too many errors

**Comment by robaho** [comment]
should be fixed now - thanks for reporting it

**Comment by ankitpatelce** [comment]
Thanks
