### ISSUE TITLE
error to build aglo

### ISSUE THREAD

**Issue by ankitpatelce** [robaho/go-trader#5]
Hello ,

when I run "go build", I have got errors like below.
Please look into it. Thanks

Also getting error in test Module

# github.com/robaho/go-trader/cmd/algo
./main.go:58:48: cannot use a.entryPrice.Add(a.offset) (type decimal.Decimal) as type fixed.Fixed in argument to price.GreaterThanOrEqual
./main.go:61:52: cannot use a.entryPrice.Sub(a.offset) (type decimal.Decimal) as type fixed.Fixed in argument to price.LessThanOrEqual

**Comment by robaho** [comment]
should be fixed now - there was more to update for the "fixed" api changes
